# frozen_string_literal: true

module Dex
  class Railtie < Rails::Railtie
    rake_tasks do
      namespace :dex do
        desc "Export operation/event/handler contracts (FORMAT=hash|json_schema SECTION=operations|events|handlers FILE=path)"
        task export: :environment do
          Rails.application.eager_load!

          format = (ENV["FORMAT"] || "hash").to_sym
          section = ENV["SECTION"] || "operations"
          file = ENV["FILE"]

          data = case section
          when "operations" then Dex::Operation.export(format: format)
          when "events" then Dex::Event.export(format: format)
          when "handlers"
            if format != :hash
              raise "Handlers only support FORMAT=hash (got #{format})"
            end

            Dex::Event::Handler.export(format: format)
          else
            raise "Unknown SECTION=#{section}. Known: operations, events, handlers"
          end

          json = JSON.pretty_generate(data)

          if file
            File.write(file, json)
            puts "Wrote #{data.size} #{section} to #{file}"
          else
            puts json
          end
        end

        desc "Install LLM guides as AGENTS.md in app directories (FORCE=1 to overwrite app-owned files)"
        task :guides do
          gem_root = File.expand_path("../..", __dir__)
          guide_dir = File.join(gem_root, "guides", "llm")
          marker = "<!-- dexkit v#{Dex::VERSION} | Auto-generated by: rake dex:guides -->"
          force = ENV["FORCE"] == "1"
          written = 0

          # [source_file, env_var, default_path]
          mapping = [
            ["OPERATION.md", "OPERATIONS_PATH", "app/operations"],
            ["EVENT.md", "EVENTS_PATH", "app/events"],
            ["EVENT.md", "EVENT_HANDLERS_PATH", "app/event_handlers"],
            ["FORM.md", "FORMS_PATH", "app/forms"],
            ["QUERY.md", "QUERIES_PATH", "app/queries"]
          ]

          mapping.each do |source_file, env_var, default_path|
            target_dir = ENV[env_var] || default_path

            unless File.directory?(target_dir)
              puts "  #{target_dir}/AGENTS.md  (skipped — directory not found)"
              next
            end

            target = File.join(target_dir, "AGENTS.md")

            if File.exist?(target) && !force
              first_line = File.open(target, &:readline).chomp rescue "" # rubocop:disable Style/RescueModifier
              unless first_line.start_with?("<!-- dexkit v")
                puts "  #{target}  (skipped — not generated by dexkit, use FORCE=1 to overwrite)"
                next
              end
            end

            source = File.join(guide_dir, source_file)
            File.write(target, "#{marker}\n\n#{File.read(source)}")
            written += 1
            puts "  #{target}  ← #{source_file}"
          end

          puts "\n#{written} guide(s) installed."
        end
      end
    end
  end
end
